config.h cleanup (#834)
config.hpp and .travis.yml cleanup

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,14 +1,20 @@
 language: cpp
 
-os:
-  - linux
-  - osx
-
-env:
-  - variant=test_release coverage=1 docs=1
-  - variant=test_debug sim=1
-  - variant=test_barebones
-  - analyze=1
+matrix:
+  include:
+    - env: variant=test_release coverage=1
+    - env: variant=test_debug sim=1
+    - env: variant=test_barebones
+    - env: analyze=1
+    - os: osx
+      osx_image: xcode6.4
+      env: variant=test_release docs=1
+    - os: osx
+      osx_image: xcode6.4
+      env: variant=test_debug
+    - os: osx
+      osx_image: xcode6.4
+      env: variant=test_barebones
 
 git:
   submodules: false
@@ -43,7 +49,7 @@ before_install:
 
   - git submodule update --init --recursive
   - 'if [[ $TRAVIS_OS_NAME == "osx" && "$variant" != "" ]]; then brew update > /dev/null && brew install --quiet ccache boost-build boost-python; fi'
-  - 'if [[ $TRAVIS_OS_NAME == "osx" && "$docs" = "1" ]]; then
+  - 'if [ "$docs" = "1" ]; then
     brew install --quiet https://raw.githubusercontent.com/catap/homebrew/docutils/Library/Formula/docutils.rb;
     mkdir -p /Users/travis/Library/Python/2.7/lib/python/site-packages;
     echo ''import site; site.addsitedir("/usr/local/lib/python2.7/site-packages")'' >> /Users/travis/Library/Python/2.7/lib/python/site-packages/homebrew.pth;
@@ -57,7 +63,7 @@ before_install:
   - if [ $TRAVIS_OS_NAME == "osx" ]; then export toolset="darwin"; export sim="0"; fi
   - if [ $TRAVIS_OS_NAME == "osx" ]; then export target="osx-tests"; fi
   - if [ $TRAVIS_OS_NAME == "linux" ]; then export toolset="gcc"; fi
-  - if [[ $TRAVIS_OS_NAME == "linux" && "$coverage" == "1" ]]; then
+  - if [ "$coverage" == "1" ]; then
     export toolset=gcc-coverage;
     pip install --user codecov;
     fi
@@ -78,13 +84,13 @@ install:
   - 'echo "using darwin : : ccache clang++ : <cflags>-std=c11 <cxxflags>-std=c++11 <compileflags>-Wno-deprecated-declarations ;" >> ~/user-config.jam'
   - 'echo "using python : 2.7 ;" >> ~/user-config.jam'
   - 'if [[ "$variant" != "" ]]; then ccache -V && ccache --show-stats && ccache --zero-stats; fi'
-  - if [[ "$docs" == "1" && $TRAVIS_OS_NAME == "osx" ]]; then rst2html.py --version; fi
+  - if [ "$docs" == "1" ]; then rst2html.py --version; fi
 
 script:
 
 
   - cd docs
-  - 'if [[ "$docs" == "1" && $TRAVIS_OS_NAME == "osx" ]]; then
+  - 'if [ "$docs" == "1" ]; then
       make RST2HTML=rst2html.py;
     fi'
   - cd ..
@@ -94,7 +100,7 @@ script:
   - cd test
   - 'if [ "$variant" != "" ]; then
       bjam -j3 warnings-as-errors=on variant=$variant -l900 $toolset $target &&
-      if [[ $TRAVIS_OS_NAME == "linux" && "$coverage" == "1" ]]; then
+      if [ "$coverage" == "1" ]; then
         codecov --root .. --gcov-exec gcov-5;
       fi;
     fi'
@@ -135,32 +141,27 @@ script:
 
 # run cppcheck if enabled
   - 'if [[ "$analyze" == "1" ]]; then
-       if [[ $TRAVIS_OS_NAME == "linux" ]]; then
-         cppcheck --version &&
-         find src test examples tools -type f | grep ".*\.cpp$" >cppcheck.files &&
-         find simulation -type f -depth -2 | grep ".*\.cpp$" >>cppcheck.files &&
-         cppcheck -DTORRENT_USE_IPV6="1" -DTORRENT_USE_I2P="1"
-           -DTORRENT_USE_OPENSSL="1" -DTORRENT_USE_INVARIANT_CHECKS="1"
-           -DTORRENT_EXPENSIVE_INVARIANT_CHECKS="1" -DTORRENT_USE_ASSERTS="1"
-           -UTORRENT_DISABLE_MUTABLE_TORRENTS -UTORRENT_DISABLE_LOGGING
-           -UTORRENT_DEBUG_BUFFERS -UTORRENT_EXPORT_EXTRA
-           --suppress=preprocessorErrorDirective
-           --suppress=noConstructor
-           --suppress=syntaxError
-           --enable=style
-           --template "{file}({line}): {severity} ({id}): {message}"
-           --inline-suppr --force --std=c++11 -j2 -I include -I /usr/local/include
-           --file-list=cppcheck.files 2> cppcheck.txt;
-         if [ -s cppcheck.txt ]; then
-           echo "   ======= CPPCHECK ERRORS =====";
-           cat cppcheck.txt;
-           exit 1;
-         fi;
-       fi;
-       if [[ $TRAVIS_OS_NAME == "osx" ]]; then
-         echo "nothing here yet";
-       fi;
-     fi'
+      cppcheck --version &&
+      find src test examples tools -type f | grep ".*\.cpp$" >cppcheck.files &&
+      find simulation -type f -depth -2 | grep ".*\.cpp$" >>cppcheck.files &&
+      cppcheck -DTORRENT_USE_IPV6="1" -DTORRENT_USE_I2P="1"
+       -DTORRENT_USE_OPENSSL="1" -DTORRENT_USE_INVARIANT_CHECKS="1"
+       -DTORRENT_EXPENSIVE_INVARIANT_CHECKS="1" -DTORRENT_USE_ASSERTS="1"
+       -UTORRENT_DISABLE_MUTABLE_TORRENTS -UTORRENT_DISABLE_LOGGING
+       -UTORRENT_DEBUG_BUFFERS -UTORRENT_EXPORT_EXTRA
+       --suppress=preprocessorErrorDirective
+       --suppress=noConstructor
+       --suppress=syntaxError
+       --enable=style
+       --template "{file}({line}): {severity} ({id}): {message}"
+       --inline-suppr --force --std=c++11 -j2 -I include -I /usr/local/include
+       --file-list=cppcheck.files 2> cppcheck.txt;
+      if [ -s cppcheck.txt ]; then
+        echo "   ======= CPPCHECK ERRORS =====";
+        cat cppcheck.txt;
+        exit 1;
+      fi;
+    fi'
 
   - 'if [[ "$variant" != "" ]]; then ccache --show-stats; fi'
 
